library(dplyr)
test_xvalues<-read.table("./test/X_test.txt")
test_yvalues<-read.table("./test/y_test.txt")
test_subjects<-read.table("./test/subject_test.txt")
train_xvalues<-read.table("./train/X_train.txt")
train_yvalues<-read.table("./train/y_train.txt")
train_subjects<-read.table("./train/subject_train.txt")
subjects<-rbind(test_subjects,train_subjects)
subjects<-rename(subjects,Subject=V1)
features<-read.table("./features.txt")
activity_labels<-read.table("./activity_labels.txt")
x_values<-rbind(test_xvalues,train_xvalues)
y_values<-rbind(test_yvalues,train_yvalues)
mean_measurements<-features[grepl("mean()",features$V2,fixed=TRUE),]
standard_measurements<-features[grep("std()",features$V2),]
measurements<-rbind(mean_measurements,standard_measurements)
measurements<-rename(measurements,colnumber=V1,colname=V2)
measurements<-arrange(measurements,colnumber)
specific_dataset<-x_values[,measurements$colnumber]
colnames(specific_dataset)<-measurements$colname
activity_names<-inner_join(y_values,activity_labels)
activity_names<-activity_names["V2"]
activity_names<-rename(activity_names,Activity=V2)
specific_dataset<-cbind(subjects,activity_names,specific_dataset)
a<-arrange(specific_dataset,Subject,Activity)
b<-group_by(a,Subject,Activity)
tidy_data<-summarise_each(b,funs(mean))
write.table(tidy_data,"./tidy_data.txt",row.names=FALSE)
